##  Artificial Neural Network Classifier 
###  Predict a student performance 
This neural network will model an one input layer (three nodes 𝑥1, 𝑥2 and b or 𝜃0), with single hidden layer (four nodes) and one output (one node). The output of the neural network model will be predicting the score of test mark based on the inputs of studying hours and sleeping hours per week.

In [43]:
import numpy as np
import matplotlib.pyplot as plt

## Dataset

In [44]:

#The input data X, (studying hours and sleeping hours per week)
X_before = np.array(([30, 50,1], [60, 80,1], [20, 30,1]), dtype=float)
#The output data Y, (total tset mark)
Y_before = np.array(([85], [95], [75]), dtype=float)


# new input data to test network 
X_Predicted_before = np.array(([[40,70,1]]), dtype=float)

# Standardization (scaled)
# X (after standardization)= old(X) / maximum of X array
X = X_before/np.amax(X_before, axis=0) 
# X_Predicted (after standardization)= old(X_Predicted) /  maximum of X_Predicted
X_Predicted = X_Predicted_before/np.amax(X_Predicted_before, axis=0)
# the total score is 100 then,the max test score is 100
Y = Y_before/100 

## Neural Network Class

In [48]:
class NeuralNetwork(object):
  def __init__(self):
  #parameters
    self.inputSize = 3
    self.hiddenSize = 4
    self.outputSize = 1

  #generate random weights from -0.5 to 0.5
    self.W1 = np.random.uniform(-0.5,0.5,(self.inputSize , self.hiddenSize)) # (3x4) weight matrix from input to hidden layer
    self.W2 = np.random.uniform(-0.5,0.5,(self.hiddenSize , self.outputSize)) # (4x1) weight matrix from hidden to output layer
    
  # feed-forward function    
  def forward(self, X):    
    self.R = np.dot(X, self.W1)  # dot product of X (input) and 3x4 weights matrix
    self.H1 = self.sigmoid(self.R) # activation function (sigmoid)
    
    self.S = np.dot(self.H1, self.W2)  # dot product of hidden layer (H1) and 4x1 weights matrix
    H2 = self.sigmoid(self.S) # final activation function (sigmoid)
    
    return H2

  # activation function
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))

  #derivative of sigmoid
  def dSigmoid(self, s):
    return s * (1 - s)

  # back-propagation function
  def backward(self, X, Y, Yhat):
    self.B2 = (Y - Yhat) * self.dSigmoid(self.S) 
    self.G2 = np.dot(self.B2.T,self.H1)

    self.B1 = np.dot(self.B2,self.W2.T)* self.dSigmoid(self.R) 
    self.G1 = np.dot(self.B1.T,X)
    
    print('W1: (weight matrix from input to hidden layer) \n',self.W1,'\n')
    print('W2: (weight matrix from hidden to output layer) \n',self.W2,'\n')
    
    self.W1 += self.G1.T #update W1
    self.W2 += self.G2.T #update W2
    
  #train function   
  def train(self, X, Y):
    Yhat = self.forward(X)
    print('R: (input of hidden layer) \n',self.R,'\n')
    print('S: (output of hidden layer) \n',self.S,'\n')
    print ("Predicted Output: (output layer at the feed forward stages) \n" + str(yHat)) # predicted the output using feedforword (predicted Y or Yhat)
    print ("\n")
    print ("SSE Error (sum square error) : " + str(np.sum(np.square(Y -Yhat)))) # SSE = sum square of (y-ŷ)2
    print ("\n")
    self.backward(X, Y, Yhat)

  #predict the result of testing dataset  
  def predict(self,X_Predicted):
    print ("*********************************")
    print ("Input: \n" + str(X_Predicted_before)) # print input X_Predicted before scaled (standardization)
    print ("Input (after scaled): \n" + str(X_Predicted));# print input X_Predicted after scaled (standardization)
    Test_Mark = self.forward(X_Predicted)
    print ("Predicted Output: " + str(Test_Mark));# predicted the output for X_Predicted input using feedforword (predicted Y or Yhat)
    print ("Predicted Test Mark:  {:.2f}".format(Test_Mark[0][0]*100))
    


## Neural Network Model

In [49]:
NN = NeuralNetwork()
print ("Input: \n" + str(X_before)) # print input X before scaled (standardization)
print ("Input (after scaled): \n" + str(X)) # print input X after scaled (standardization)
print ("Actual Output: \n" + str(Y)) # print true Y
print ("\n")

for i in range(3):       
    print ("*********************************")
    print ("Iteration number " + str(i) )
    print ("*********************************")
    print ("\n")
    NN.train(X, Y) # train the network

#Test and report the result of classifying the testing example
NN.predict(X_Predicted)


Input: 
[[30. 50.  1.]
 [60. 80.  1.]
 [20. 30.  1.]]
Input (after scaled): 
[[0.5        0.625      1.        ]
 [1.         1.         1.        ]
 [0.33333333 0.375      1.        ]]
Actual Output: 
[[0.85]
 [0.95]
 [0.75]]


*********************************
Iteration number 0
*********************************


R: (input of hidden layer) 
 [[-0.13521054  0.16937851  0.15149833 -0.02832529]
 [-0.1849983   0.20875965  0.084269    0.10382305]
 [-0.17265768  0.15290775  0.21449302 -0.12333818]] 

S: (output of hidden layer) 
 [[0.48045966]
 [0.49113474]
 [0.47654374]] 

Predicted Output: (output layer at the feed forward stages) 
[[0.5]
 [0.5]
 [0.5]]


SSE Error (sum square error) : 0.18025138844069402


W1: (weight matrix from input to hidden layer) 
 [[-0.4238339   0.05869997  0.10905084 -0.04148394]
 [ 0.4323445   0.02674974 -0.32467933  0.40770751]
 [-0.1935089   0.12330994  0.29989749 -0.26240052]] 

W2: (weight matrix from hidden to output layer) 
 [[-0.1011726 ]
 [ 0.13561229]